// ------------------------------------------------------------------
// Central data source for the Current Events listing
// (pages/current-events.html), the Admissions "Current Events" filter
// card (pages/admissions.html + admissions.js), and the Event Details
// template (pages/event-details.html?id=<key>). One record per event,
// keyed by id - same data-driven pattern as pages/news/news-data.js.
//
// The first 3 entries are migrated as-is from the inline
// `filterCategories.events` array that used to live in admissions.js -
// same headline/excerpt/date/image content, just moved here so the
// listing/detail pages and the Admissions card share one source
// instead of duplicating these items.
//
// `showOnAdmissions: true` marks an item as one of the items the
// Admissions page's "Current Events" filter card cycles through - same
// hand-maintained stand-in for the future admin panel's per-item
// toggle as newsData's showOnAdmissions flag.
//
// `excerpt` is only shown on the Admissions card, so it's only filled
// in for showOnAdmissions items.
//
// `body` holds the same placeholder paragraph copy used across
// News/Notices until real per-event article text is written.
//
// `createdOrder` is assigned once, in creation order, and never changes -
// same permanent-identity pattern as jobCircularData's createdOrder
// (pages/job-circular/job-circular-data.js) and newsData's createdOrder.
// Every list/carousel that reads this file (current-events.html, the
// Admissions "Current Events" card) sorts by createdOrder descending so
// the newest-added event always shows first, regardless of its `date`.
//
// Paths below are relative to pages/ (current-events.html, admissions.html
// and event-details.html all live at that same depth).
// ------------------------------------------------------------------
const eventsPlaceholderBody = [
  "Choosing a university is an important decision that shapes a student’s academic journey, personal development, and future career. RTM Al-Kabir Technical University (RTM-AKTU) is committed to providing a modern, inclusive, and career-focused learning environment where students can develop the knowledge, skills, creativity, and confidence needed to succeed in a rapidly changing world. With a strong emphasis on quality education, experienced faculty members, practical learning, research and innovation, and professional development, RTM-AKTU seeks to bridge the gap between academic knowledge and real-world requirements.",
  "The university encourages students to think critically, explore new ideas, engage in meaningful research, and gain practical experience beyond the traditional classroom. A contemporary campus environment, dedicated and knowledgeable faculty, opportunities for research and innovation, and strong career-oriented support together create an educational experience designed to prepare graduates for higher studies, professional careers, entrepreneurship, and meaningful contributions to society. At RTM-AKTU, students are not simply prepared to earn a degree—they are encouraged to build the competence, character, and confidence to shape their own future.",
];

// @admin-export-start eventsData
// Everything between these two marker lines is regenerated by the admin
// panel (self-bhalani/event-list.php) from the database on every save -
// edit events there, not here. Hidden items are left out of this block.
const eventsData = {
  'orientation-day-for-new-undergraduate-students': {
    createdOrder: 1,
    headline: 'Orientation Day for New Undergraduate Students',
    date: '2026-09-02',
    image: '../images/current-events/event-01.jpg',
    showOnAdmissions: true,
    excerpt: 'Join us for a full day of campus tours, faculty introductions, and academic advising ahead of the new semester.',
    body: eventsPlaceholderBody,
  },
  'annual-tech-fest-2026-opens-registration-for-student-teams': {
    createdOrder: 2,
    headline: 'Annual Tech Fest 2026 Opens Registration for Student Teams',
    date: '2026-09-20',
    image: '../images/current-events/event-02.jpg',
    showOnAdmissions: true,
    excerpt: 'Students from all departments can now register for this year\'s hackathon, robotics showcase, and innovation exhibits.',
    body: eventsPlaceholderBody,
  },
  'career-fair-brings-regional-employers-to-campus': {
    createdOrder: 3,
    headline: 'Career Fair Brings Regional Employers to Campus',
    date: '2026-10-10',
    image: '../images/current-events/event-03.jpg',
    showOnAdmissions: true,
    excerpt: 'Final-year students are invited to meet recruiters from partner companies for internship and job placement opportunities.',
    body: eventsPlaceholderBody,
  },
};
// @admin-export-end eventsData

// Shared date helpers so the listing, the Admissions card, and the
// details page all format the same ISO `date` value the same way -
// same helpers as formatNewsDateLong/Short/Weekday in news-data.js.
function formatEventDateLong(isoDate) {
  const date = new Date(`${isoDate}T00:00:00`);
  return date.toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' });
}

function formatEventDateShort(isoDate) {
  const date = new Date(`${isoDate}T00:00:00`);
  return date.toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' });
}

function formatEventWeekday(isoDate) {
  const date = new Date(`${isoDate}T00:00:00`);
  return date.toLocaleDateString('en-US', { weekday: 'long' });
}

// Headline/body text comes from the admin panel, so every listing that
// builds HTML with a template string runs it through this first - a `<`
// or `"` in a headline must print as text, never become markup.
function escapeEventHtml(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// A record's `body` is either an array of plain-text paragraphs, or (when
// written with the admin panel's rich-text editor) a string of HTML. That
// HTML is already sanitized by the admin panel before it is saved; it is
// rebuilt here once more through the same allow-list (eventSanitizeHtml()
// in self-bhalani/event-lib.php - keep the two in step), element by element
// with createElement/textContent, so a hand-edited file can't inject
// markup either. The site's own body-copy classes are added on the way.
const EVENT_HTML_RULES = {
  P: { tag: 'p', className: 'text-section__text', styleProps: ['text-align', 'margin-left', 'line-height'] },
  H3: { tag: 'h3', className: 'cm-content__heading', styleProps: ['text-align', 'margin-left', 'line-height'] },
  H4: { tag: 'h4', className: 'text-section__subheading', styleProps: ['text-align', 'margin-left', 'line-height'] },
  LI: { tag: 'li', styleProps: ['text-align', 'margin-left', 'line-height'] },
  UL: { tag: 'ul', className: 'text-section__list' },
  OL: { tag: 'ol', className: 'text-section__list text-section__list--ordered' },
  STRONG: { tag: 'strong' }, B: { tag: 'strong' },
  EM: { tag: 'em' }, I: { tag: 'em' },
  U: { tag: 'u' },
  // Text/background color (forecolor/backcolor), font family/size/weight -
  // all always arrive wrapped in a <span style="..."> by TinyMCE.
  SPAN: { tag: 'span', styleProps: ['color', 'background-color', 'font-family', 'font-size', 'font-weight'] },
  BR: { tag: 'br' },
  A: { tag: 'a', className: 'text-section__link' },
  IMG: { tag: 'img', className: 'news-inline-img' },
  // Tables from the editor's table plugin. The table's default look
  // (padding, header shading, base grid) comes from style.css
  // (.news-detail-text table) - a cell's/row's own background-color/border
  // (set via the editor's "Cell properties"/"Row properties" Advanced tab)
  // overrides that default, since inline style wins over the class rule
  // (mirrors EVENT_STYLE_ALLOWED in self-bhalani/event-lib.php).
  TABLE: { tag: 'table' },
  THEAD: { tag: 'thead' },
  TBODY: { tag: 'tbody' },
  TR: { tag: 'tr', styleProps: ['background-color', 'border', 'border-width', 'border-style', 'border-color'] },
  // border-top/-right/-bottom/-left: the editor's per-side cell border
  // controls (Cell Color & Border button) - mirrors EVENT_STYLE_ALLOWED in
  // self-bhalani/event-lib.php, keep the two in step.
  TH: {
    tag: 'th',
    styleProps: ['text-align', 'background-color', 'border', 'border-width', 'border-style', 'border-color',
      'border-top', 'border-right', 'border-bottom', 'border-left'],
    cell: true,
  },
  TD: {
    tag: 'td',
    styleProps: ['text-align', 'background-color', 'border', 'border-width', 'border-style', 'border-color',
      'border-top', 'border-right', 'border-bottom', 'border-left'],
    cell: true,
  },
};
const EVENT_HTML_DROP = new Set(['SCRIPT', 'STYLE', 'IFRAME', 'FRAME', 'FRAMESET', 'OBJECT', 'EMBED', 'APPLET', 'TEMPLATE',
  'SVG', 'MATH', 'NOSCRIPT', 'TEXTAREA', 'SELECT', 'BUTTON', 'INPUT', 'FORM', 'HEAD', 'TITLE', 'META', 'LINK', 'BASE',
  'VIDEO', 'AUDIO', 'CANVAS']);
const EVENT_IMG_CLASSES = ['news-inline-img--left', 'news-inline-img--left-sm', 'news-inline-img--right',
  'news-inline-img--right-sm', 'news-inline-img--center'];
const EVENT_IMG_SRC_RE = /^\.\.\/images\/current-events-body\/[A-Za-z0-9_-]+\.(?:jpg|png|webp)$/;

function eventSafeHref(href) {
  const value = href.trim();
  if (!value) return null;
  const scheme = value.replace(/[\x00-\x20\x7F]+/g, '').match(/^([a-z][a-z0-9+.-]*):/i);
  if (scheme && !['http', 'https', 'mailto', 'tel'].includes(scheme[1].toLowerCase())) return null;
  return value;
}

// font-family/font-size/font-weight are matched against these fixed lists
// (not a free-form regex) - only the site's own two brand fonts, and only
// the sizes/weights the editor's own dropdowns offer, ever reach the page.
// Keep in step with EVENT_FONT_FAMILIES/SIZES/WEIGHTS in self-bhalani/event-lib.php.
const EVENT_FONT_FAMILIES = { 'inter, sans-serif': 'Inter, sans-serif', 'poppins, sans-serif': 'Poppins, sans-serif' };
const EVENT_FONT_SIZES = ['12px', '14px', '15px', '16px', '18px', '20px', '24px', '28px', '32px'];
const EVENT_FONT_WEIGHTS = ['300', '400', '500', '600', '700', '800'];

// Matches either #hex or the browser's rgb()/rgba() form - TinyMCE's own
// getContent() re-serializes any color inside a compound value (border-top/
// -right/-bottom/-left, the plain 'border' shorthand, border-color) as
// rgb(r, g, b) even though the editor's color picker supplied hex; a plain
// background-color/color is left as the authored hex. Both forms need
// accepting here or the "Cell Color & Border" dialog's border colors would
// be silently stripped. Mirrors EVENT_COLOR_RE in self-bhalani/event-lib.php.
const EVENT_COLOR_RE_SRC = '(#[0-9a-f]{3}(?:[0-9a-f]{3})?|rgba?\\(\\s*\\d{1,3}\\s*,\\s*\\d{1,3}\\s*,\\s*\\d{1,3}\\s*(?:,\\s*[0-9.]+\\s*)?\\))';

// Normalizes either color form above to lowercase #rrggbb, or returns null
// if it's neither. Mirrors eventColorToHex() in self-bhalani/event-lib.php.
function eventColorToHex(val) {
  const v = val.trim();
  if (/^#[0-9a-f]{3}(?:[0-9a-f]{3})?$/i.test(v)) return v.toLowerCase();
  const m = v.match(/^rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*(?:,\s*[0-9.]+\s*)?\)$/i);
  if (!m) return null;
  const clamp = (n) => Math.max(0, Math.min(255, Number(n)));
  return '#' + [m[1], m[2], m[3]].map((n) => clamp(n).toString(16).padStart(2, '0')).join('');
}

// Editor-supplied style attribute -> only the declarations `styleProps`
// permits, with each value itself checked against a fixed pattern or list -
// never passed through as free-form CSS. Mirrors eventCleanStyle() in
// self-bhalani/event-lib.php - keep the two in step.
function eventCleanStyle(styleProps, styleAttr) {
  const out = [];
  (styleAttr || '').split(';').forEach((decl) => {
    const m = decl.match(/^\s*([a-z-]+)\s*:\s*(.+?)\s*$/i);
    if (!m) return;
    const prop = m[1].toLowerCase();
    const val = m[2].trim();
    if (!styleProps.includes(prop)) return;
    let hex;
    if (prop === 'text-align' && /^(left|center|right|justify)$/i.test(val)) {
      out.push(`text-align: ${val.toLowerCase()}`);
    } else if ((prop === 'color' || prop === 'background-color') && (hex = eventColorToHex(val)) !== null) {
      out.push(`${prop}: ${hex}`);
    } else if (prop === 'margin-left') {
      const mm = val.match(/^([0-9]{1,3})px$/);
      if (mm && Number(mm[1]) <= 200) out.push(`margin-left: ${Number(mm[1])}px`);
    } else if (prop === 'line-height' && /^[0-3](?:\.[0-9]{1,2})?$/.test(val)) {
      out.push(`line-height: ${val}`);
    } else if (prop === 'font-family') {
      const norm = val.trim().replace(/^["']|["']$/g, '').toLowerCase().replace(/\s*,\s*/g, ', ');
      if (EVENT_FONT_FAMILIES[norm]) out.push(`font-family: ${EVENT_FONT_FAMILIES[norm]}`);
    } else if (prop === 'font-size' && EVENT_FONT_SIZES.includes(val)) {
      out.push(`font-size: ${val}`);
    } else if (prop === 'font-weight' && EVENT_FONT_WEIGHTS.includes(val)) {
      out.push(`font-weight: ${val}`);
    } else if (prop === 'border-width') {
      const mm = val.match(/^([0-9]{1,2})px$/);
      if (mm && Number(mm[1]) >= 1 && Number(mm[1]) <= 10) out.push(`border-width: ${Number(mm[1])}px`);
    } else if (prop === 'border-style' && /^(none|solid|dashed|dotted|double|groove|ridge|inset|outset)$/i.test(val)) {
      out.push(`border-style: ${val.toLowerCase()}`);
    } else if (prop === 'border-color' && (hex = eventColorToHex(val)) !== null) {
      out.push(`border-color: ${hex}`);
    } else if (prop === 'border') {
      const mm = val.match(new RegExp(`^([0-9]{1,2})px\\s+(none|solid|dashed|dotted|double|groove|ridge|inset|outset)\\s+${EVENT_COLOR_RE_SRC}$`, 'i'));
      if (mm && Number(mm[1]) <= 10 && (hex = eventColorToHex(mm[3])) !== null) {
        out.push(`border: ${Number(mm[1])}px ${mm[2].toLowerCase()} ${hex}`);
      }
    } else if (['border-top', 'border-right', 'border-bottom', 'border-left'].includes(prop)) {
      const mm = val.match(new RegExp(`^([0-9]{1,2})px\\s+(none|solid|dashed|dotted|double|groove|ridge|inset|outset)\\s+${EVENT_COLOR_RE_SRC}$`, 'i'));
      if (mm && Number(mm[1]) <= 10 && (hex = eventColorToHex(mm[3])) !== null) {
        out.push(`${prop}: ${Number(mm[1])}px ${mm[2].toLowerCase()} ${hex}`);
      }
    }
  });
  return out.length ? `${out.join('; ')};` : '';
}

function sanitizeEventHtml(html) {
  // DOMParser documents are inert: nothing in them runs or loads.
  const source = new DOMParser().parseFromString(`<body>${html}</body>`, 'text/html').body;
  const fragment = document.createDocumentFragment();
  source.childNodes.forEach((child) => appendCleanEventNode(child, fragment));
  return fragment;
}

function appendCleanEventNode(node, parent) {
  if (node.nodeType === Node.TEXT_NODE) {
    parent.appendChild(document.createTextNode(node.textContent));
    return;
  }
  if (node.nodeType !== Node.ELEMENT_NODE || EVENT_HTML_DROP.has(node.tagName.toUpperCase())) return;

  const rule = EVENT_HTML_RULES[node.tagName.toUpperCase()];
  let target = parent; // unknown tag: keep its text, drop the tag
  if (rule) {
    const el = document.createElement(rule.tag);
    if (rule.className) el.className = rule.className;

    if (rule.tag === 'img') {
      const src = (node.getAttribute('src') || '').trim();
      if (!EVENT_IMG_SRC_RE.test(src)) return;
      el.src = src;
      el.alt = node.getAttribute('alt') || '';
      el.loading = 'lazy';
      const floatClass = (node.getAttribute('class') || '').split(/\s+/).find((c) => EVENT_IMG_CLASSES.includes(c));
      if (floatClass) el.classList.add(floatClass);
      parent.appendChild(el);
      return;
    }
    if (rule.tag === 'a') {
      const href = eventSafeHref(node.getAttribute('href') || '');
      if (href !== null) {
        el.href = href;
        if (node.getAttribute('target') === '_blank') {
          el.target = '_blank';
          el.rel = 'noopener noreferrer';
        }
        target = el;
      }
    } else {
      target = el;
    }
    if (rule.styleProps) {
      const style = eventCleanStyle(rule.styleProps, node.getAttribute('style') || '');
      if (style) el.setAttribute('style', style);
    }
    if (rule.cell) {
      ['colspan', 'rowspan'].forEach((attr) => {
        const v = (node.getAttribute(attr) || '').trim();
        if (/^[1-9][0-9]?$/.test(v)) el.setAttribute(attr, v);
      });
    }
    if (target === el) parent.appendChild(el);
  }
  node.childNodes.forEach((child) => appendCleanEventNode(child, target));
}

// Fills `container` with a record's body in either of its two shapes: an
// array of plain-text paragraphs (the seed data, eventsPlaceholderBody,
// and anything saved with only plain paragraphs - see eventBodyForStorage()
// in self-bhalani/event-lib.php), or a string of editor HTML.
function renderEventBody(body, container) {
  if (Array.isArray(body)) {
    container.innerHTML = body
      .map((paragraph) => `<p class="text-section__text">${escapeEventHtml(paragraph)}</p>`)
      .join('');
    return;
  }
  container.replaceChildren(sanitizeEventHtml(String(body || '')));
}
