// ------------------------------------------------------------------
// Central data source for the University News listing
// (pages/university-news.html), the Admissions "Current News" carousel
// (pages/admissions.html + admissions.js), and the News Details template
// (pages/news-details.html?id=<key>). One record per news item, keyed by
// id - no HTML markup to duplicate across pages.
//
// `showOnAdmissions: true` marks an item as one of the items the
// Admissions page's "Current News" carousel cycles through. This is the
// hand-maintained stand-in for the per-item "show on Admissions" toggle
// the future admin panel will expose - flip this flag instead of adding
// a new hardcoded carousel entry once that panel exists.
//
// `excerpt` is only shown on the Admissions carousel card, so it's only
// filled in for showOnAdmissions items.
//
// `body` holds placeholder paragraph copy (from the Figma News Details
// design) reused across every item until real per-item article text is
// written - same handling as the faculty-profile boilerplate blocks.
// A body is either an array of plain-text paragraphs or, for an item
// written with formatting in the admin panel's editor, one HTML string -
// renderNewsBody() at the bottom of this file handles both.
//
// `createdOrder` is assigned once, in creation order, and never changes -
// same permanent-identity pattern as jobCircularData's createdOrder
// (pages/job-circular/job-circular-data.js). Every list/carousel that reads
// this file (university-news.html, the Admissions "Current News" carousel,
// the home page's Current News list) sorts by createdOrder descending so
// the newest-added item always shows first, regardless of its `date`.
//
// Paths below are relative to pages/ (university-news.html, admissions.html
// and news-details.html all live at that same depth).
// ------------------------------------------------------------------
const newsPlaceholderBody = [
  "Choosing a university is an important decision that shapes a student’s academic journey, personal development, and future career. RTM Al-Kabir Technical University (RTM-AKTU) is committed to providing a modern, inclusive, and career-focused learning environment where students can develop the knowledge, skills, creativity, and confidence needed to succeed in a rapidly changing world. With a strong emphasis on quality education, experienced faculty members, practical learning, research and innovation, and professional development, RTM-AKTU seeks to bridge the gap between academic knowledge and real-world requirements.",
  "The university encourages students to think critically, explore new ideas, engage in meaningful research, and gain practical experience beyond the traditional classroom. A contemporary campus environment, dedicated and knowledgeable faculty, opportunities for research and innovation, and strong career-oriented support together create an educational experience designed to prepare graduates for higher studies, professional careers, entrepreneurship, and meaningful contributions to society. At RTM-AKTU, students are not simply prepared to earn a degree—they are encouraged to build the competence, character, and confidence to shape their own future.",
];

// @admin-export-start newsData
// Everything between these two marker lines is regenerated by the admin
// panel (self-bhalani/news-list.php) from the database on every save -
// edit news there, not here. Hidden items are left out of this block.
const newsData = {
  'rtm-aktu-hosts-international-research-conference-2026': {
    createdOrder: 1,
    headline: 'RTM-AKTU Hosts International Research Conference 2026',
    date: '2026-08-28',
    image: '../images/university-news/news-01.jpg',
    showOnAdmissions: false,
    showOnHome: true,
    body: newsPlaceholderBody,
  },
  'new-academic-programs-introduced-this-semester': {
    createdOrder: 2,
    headline: 'New Academic Programs Introduced This Semester.',
    date: '2026-08-26',
    image: '../images/university-news/news-02.jpg',
    showOnAdmissions: false,
    showOnHome: false,
    body: newsPlaceholderBody,
  },
  'students-achieve-outstanding-results-in-national-competitions': {
    createdOrder: 3,
    headline: 'Students Achieve Outstanding Results in National Competitions',
    date: '2026-08-26',
    image: '../images/university-news/news-03.jpg',
    showOnAdmissions: false,
    showOnHome: true,
    body: newsPlaceholderBody,
  },
  'ugc-member-inaugurates-laboratories': {
    createdOrder: 4,
    headline: "Professor Dr. Anwar Hossain, Honorable Member of the UGC, officially inaugurated the laboratories during his visit to RTM-AKTU on Sept. 20, 2025.",
    date: '2026-08-26',
    image: '../images/university-news/news-04.jpg',
    showOnAdmissions: false,
    showOnHome: false,
    body: newsPlaceholderBody,
  },
  'rtm-aktu-opens-admission-window-for-upcoming-academic-session': {
    createdOrder: 5,
    headline: 'RTM-AKTU Opens Admission Window for Upcoming Academic Session',
    date: '2026-08-18',
    image: '../images/admissions/news-1.jpg',
    showOnAdmissions: true,
    showOnHome: true,
    excerpt: 'Prospective students can now begin the application process for undergraduate and postgraduate programs across all faculties.',
    body: newsPlaceholderBody,
  },
  'new-scholarship-fund-launched-for-first-generation-university-students': {
    createdOrder: 6,
    headline: 'New Scholarship Fund Launched for First-Generation University Students',
    date: '2026-08-25',
    image: '../images/admissions/news-2.jpg',
    showOnAdmissions: true,
    showOnHome: false,
    excerpt: 'The scholarship office has opened applications for a new needs-based fund supporting students who are the first in their family to attend university.',
    body: newsPlaceholderBody,
  },
  'department-of-cse-signs-research-partnership-with-regional-tech-firm': {
    createdOrder: 7,
    headline: 'Department of CSE Signs Research Partnership with Regional Tech Firm',
    date: '2026-09-05',
    image: '../images/admissions/news-3.jpg',
    showOnAdmissions: true,
    showOnHome: false,
    excerpt: 'The partnership will fund joint research projects and create new internship placements for undergraduate students starting next semester.',
    body: newsPlaceholderBody,
  },
};
// @admin-export-end newsData

// Shared date helpers so the listing, the carousel and the details page
// all format the same ISO `date` value the same way.
function formatNewsDateLong(isoDate) {
  const date = new Date(`${isoDate}T00:00:00`);
  return date.toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' });
}

function formatNewsDateShort(isoDate) {
  const date = new Date(`${isoDate}T00:00:00`);
  return date.toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' });
}

function formatNewsWeekday(isoDate) {
  const date = new Date(`${isoDate}T00:00:00`);
  return date.toLocaleDateString('en-US', { weekday: 'long' });
}

// Headline/body text comes from the admin panel, so every listing that
// builds HTML with a template string runs it through this first - a `<`
// or `"` in a headline must print as text, never become markup.
function escapeNewsHtml(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// A record's `body` is either an array of plain-text paragraphs, or (when
// written with the admin panel's rich-text editor) a string of HTML. That
// HTML is already sanitized by the admin panel before it is saved; it is
// rebuilt here once more through the same allow-list (newsSanitizeHtml()
// in self-bhalani/news-lib.php - keep the two in step), element by element
// with createElement/textContent, so a hand-edited file can't inject
// markup either. The site's own body-copy classes are added on the way.
const NEWS_HTML_RULES = {
  P: { tag: 'p', className: 'text-section__text', styleProps: ['text-align', 'margin-left', 'line-height'] },
  H3: { tag: 'h3', className: 'cm-content__heading', styleProps: ['text-align', 'margin-left', 'line-height'] },
  H4: { tag: 'h4', className: 'text-section__subheading', styleProps: ['text-align', 'margin-left', 'line-height'] },
  LI: { tag: 'li', styleProps: ['text-align', 'margin-left', 'line-height'] },
  UL: { tag: 'ul', className: 'text-section__list' },
  OL: { tag: 'ol', className: 'text-section__list text-section__list--ordered' },
  STRONG: { tag: 'strong' }, B: { tag: 'strong' },
  EM: { tag: 'em' }, I: { tag: 'em' },
  U: { tag: 'u' },
  // Text/background color (forecolor/backcolor), font family/size/weight -
  // all always arrive wrapped in a <span style="..."> by TinyMCE.
  SPAN: { tag: 'span', styleProps: ['color', 'background-color', 'font-family', 'font-size', 'font-weight'] },
  BR: { tag: 'br' },
  A: { tag: 'a', className: 'text-section__link' },
  IMG: { tag: 'img', className: 'news-inline-img' },
  // Tables from the editor's table plugin. The table's default look
  // (padding, header shading, base grid) comes from style.css
  // (.news-detail-text table) - a cell's/row's own background-color/border
  // (set via the editor's "Cell properties"/"Row properties" Advanced tab)
  // overrides that default, since inline style wins over the class rule
  // (mirrors NEWS_STYLE_ALLOWED in self-bhalani/news-lib.php).
  TABLE: { tag: 'table' },
  THEAD: { tag: 'thead' },
  TBODY: { tag: 'tbody' },
  TR: { tag: 'tr', styleProps: ['background-color', 'border', 'border-width', 'border-style', 'border-color'] },
  // border-top/-right/-bottom/-left: the editor's per-side cell border
  // controls (Cell Color & Border button) - mirrors NEWS_STYLE_ALLOWED in
  // self-bhalani/news-lib.php, keep the two in step.
  TH: {
    tag: 'th',
    styleProps: ['text-align', 'background-color', 'border', 'border-width', 'border-style', 'border-color',
      'border-top', 'border-right', 'border-bottom', 'border-left'],
    cell: true,
  },
  TD: {
    tag: 'td',
    styleProps: ['text-align', 'background-color', 'border', 'border-width', 'border-style', 'border-color',
      'border-top', 'border-right', 'border-bottom', 'border-left'],
    cell: true,
  },
};
const NEWS_HTML_DROP = new Set(['SCRIPT', 'STYLE', 'IFRAME', 'FRAME', 'FRAMESET', 'OBJECT', 'EMBED', 'APPLET', 'TEMPLATE',
  'SVG', 'MATH', 'NOSCRIPT', 'TEXTAREA', 'SELECT', 'BUTTON', 'INPUT', 'FORM', 'HEAD', 'TITLE', 'META', 'LINK', 'BASE',
  'VIDEO', 'AUDIO', 'CANVAS']);
const NEWS_IMG_CLASSES = ['news-inline-img--left', 'news-inline-img--left-sm', 'news-inline-img--right',
  'news-inline-img--right-sm', 'news-inline-img--center'];
const NEWS_IMG_SRC_RE = /^\.\.\/images\/university-news\/[A-Za-z0-9_-]+\.(?:jpg|png|webp)$/;

function newsSafeHref(href) {
  const value = href.trim();
  if (!value) return null;
  const scheme = value.replace(/[\x00-\x20\x7F]+/g, '').match(/^([a-z][a-z0-9+.-]*):/i);
  if (scheme && !['http', 'https', 'mailto', 'tel'].includes(scheme[1].toLowerCase())) return null;
  return value;
}

// font-family/font-size/font-weight are matched against these fixed lists
// (not a free-form regex) - only the site's own two brand fonts, and only
// the sizes/weights the editor's own dropdowns offer, ever reach the page.
// Keep in step with NEWS_FONT_FAMILIES/SIZES/WEIGHTS in self-bhalani/news-lib.php.
const NEWS_FONT_FAMILIES = { 'inter, sans-serif': 'Inter, sans-serif', 'poppins, sans-serif': 'Poppins, sans-serif' };
const NEWS_FONT_SIZES = ['12px', '14px', '15px', '16px', '18px', '20px', '24px', '28px', '32px'];
const NEWS_FONT_WEIGHTS = ['300', '400', '500', '600', '700', '800'];

// Matches either #hex or the browser's rgb()/rgba() form - TinyMCE's own
// getContent() re-serializes any color inside a compound value (border-top/
// -right/-bottom/-left, the plain 'border' shorthand, border-color) as
// rgb(r, g, b) even though the editor's color picker supplied hex; a plain
// background-color/color is left as the authored hex. Both forms need
// accepting here or the "Cell Color & Border" dialog's border colors would
// be silently stripped. Mirrors NEWS_COLOR_RE in self-bhalani/news-lib.php.
const NEWS_COLOR_RE_SRC = '(#[0-9a-f]{3}(?:[0-9a-f]{3})?|rgba?\\(\\s*\\d{1,3}\\s*,\\s*\\d{1,3}\\s*,\\s*\\d{1,3}\\s*(?:,\\s*[0-9.]+\\s*)?\\))';

// Normalizes either color form above to lowercase #rrggbb, or returns null
// if it's neither. Mirrors newsColorToHex() in self-bhalani/news-lib.php.
function newsColorToHex(val) {
  const v = val.trim();
  if (/^#[0-9a-f]{3}(?:[0-9a-f]{3})?$/i.test(v)) return v.toLowerCase();
  const m = v.match(/^rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*(?:,\s*[0-9.]+\s*)?\)$/i);
  if (!m) return null;
  const clamp = (n) => Math.max(0, Math.min(255, Number(n)));
  return '#' + [m[1], m[2], m[3]].map((n) => clamp(n).toString(16).padStart(2, '0')).join('');
}

// Editor-supplied style attribute -> only the declarations `styleProps`
// permits, with each value itself checked against a fixed pattern or list -
// never passed through as free-form CSS. Mirrors newsCleanStyle() in
// self-bhalani/news-lib.php - keep the two in step.
function newsCleanStyle(styleProps, styleAttr) {
  const out = [];
  (styleAttr || '').split(';').forEach((decl) => {
    const m = decl.match(/^\s*([a-z-]+)\s*:\s*(.+?)\s*$/i);
    if (!m) return;
    const prop = m[1].toLowerCase();
    const val = m[2].trim();
    if (!styleProps.includes(prop)) return;
    let hex;
    if (prop === 'text-align' && /^(left|center|right|justify)$/i.test(val)) {
      out.push(`text-align: ${val.toLowerCase()}`);
    } else if ((prop === 'color' || prop === 'background-color') && (hex = newsColorToHex(val)) !== null) {
      out.push(`${prop}: ${hex}`);
    } else if (prop === 'margin-left') {
      const mm = val.match(/^([0-9]{1,3})px$/);
      if (mm && Number(mm[1]) <= 200) out.push(`margin-left: ${Number(mm[1])}px`);
    } else if (prop === 'line-height' && /^[0-3](?:\.[0-9]{1,2})?$/.test(val)) {
      out.push(`line-height: ${val}`);
    } else if (prop === 'font-family') {
      const norm = val.trim().replace(/^["']|["']$/g, '').toLowerCase().replace(/\s*,\s*/g, ', ');
      if (NEWS_FONT_FAMILIES[norm]) out.push(`font-family: ${NEWS_FONT_FAMILIES[norm]}`);
    } else if (prop === 'font-size' && NEWS_FONT_SIZES.includes(val)) {
      out.push(`font-size: ${val}`);
    } else if (prop === 'font-weight' && NEWS_FONT_WEIGHTS.includes(val)) {
      out.push(`font-weight: ${val}`);
    } else if (prop === 'border-width') {
      const mm = val.match(/^([0-9]{1,2})px$/);
      if (mm && Number(mm[1]) >= 1 && Number(mm[1]) <= 10) out.push(`border-width: ${Number(mm[1])}px`);
    } else if (prop === 'border-style' && /^(none|solid|dashed|dotted|double|groove|ridge|inset|outset)$/i.test(val)) {
      out.push(`border-style: ${val.toLowerCase()}`);
    } else if (prop === 'border-color' && (hex = newsColorToHex(val)) !== null) {
      out.push(`border-color: ${hex}`);
    } else if (prop === 'border') {
      const mm = val.match(new RegExp(`^([0-9]{1,2})px\\s+(none|solid|dashed|dotted|double|groove|ridge|inset|outset)\\s+${NEWS_COLOR_RE_SRC}$`, 'i'));
      if (mm && Number(mm[1]) <= 10 && (hex = newsColorToHex(mm[3])) !== null) {
        out.push(`border: ${Number(mm[1])}px ${mm[2].toLowerCase()} ${hex}`);
      }
    } else if (['border-top', 'border-right', 'border-bottom', 'border-left'].includes(prop)) {
      const mm = val.match(new RegExp(`^([0-9]{1,2})px\\s+(none|solid|dashed|dotted|double|groove|ridge|inset|outset)\\s+${NEWS_COLOR_RE_SRC}$`, 'i'));
      if (mm && Number(mm[1]) <= 10 && (hex = newsColorToHex(mm[3])) !== null) {
        out.push(`${prop}: ${Number(mm[1])}px ${mm[2].toLowerCase()} ${hex}`);
      }
    }
  });
  return out.length ? `${out.join('; ')};` : '';
}

function sanitizeNewsHtml(html) {
  // DOMParser documents are inert: nothing in them runs or loads.
  const source = new DOMParser().parseFromString(`<body>${html}</body>`, 'text/html').body;
  const fragment = document.createDocumentFragment();
  source.childNodes.forEach((child) => appendCleanNewsNode(child, fragment));
  return fragment;
}

function appendCleanNewsNode(node, parent) {
  if (node.nodeType === Node.TEXT_NODE) {
    parent.appendChild(document.createTextNode(node.textContent));
    return;
  }
  if (node.nodeType !== Node.ELEMENT_NODE || NEWS_HTML_DROP.has(node.tagName.toUpperCase())) return;

  const rule = NEWS_HTML_RULES[node.tagName.toUpperCase()];
  let target = parent; // unknown tag: keep its text, drop the tag
  if (rule) {
    const el = document.createElement(rule.tag);
    if (rule.className) el.className = rule.className;

    if (rule.tag === 'img') {
      const src = (node.getAttribute('src') || '').trim();
      if (!NEWS_IMG_SRC_RE.test(src)) return;
      el.src = src;
      el.alt = node.getAttribute('alt') || '';
      el.loading = 'lazy';
      const floatClass = (node.getAttribute('class') || '').split(/\s+/).find((c) => NEWS_IMG_CLASSES.includes(c));
      if (floatClass) el.classList.add(floatClass);
      parent.appendChild(el);
      return;
    }
    if (rule.tag === 'a') {
      const href = newsSafeHref(node.getAttribute('href') || '');
      if (href !== null) {
        el.href = href;
        if (node.getAttribute('target') === '_blank') {
          el.target = '_blank';
          el.rel = 'noopener noreferrer';
        }
        target = el;
      }
    } else {
      target = el;
    }
    if (rule.styleProps) {
      const style = newsCleanStyle(rule.styleProps, node.getAttribute('style') || '');
      if (style) el.setAttribute('style', style);
    }
    if (rule.cell) {
      ['colspan', 'rowspan'].forEach((attr) => {
        const v = (node.getAttribute(attr) || '').trim();
        if (/^[1-9][0-9]?$/.test(v)) el.setAttribute(attr, v);
      });
    }
    if (target === el) parent.appendChild(el);
  }
  node.childNodes.forEach((child) => appendCleanNewsNode(child, target));
}

// Fills `container` with a record's body in either of its two shapes.
function renderNewsBody(body, container) {
  if (Array.isArray(body)) {
    container.innerHTML = body
      .map((paragraph) => `<p class="text-section__text">${escapeNewsHtml(paragraph)}</p>`)
      .join('');
    return;
  }
  container.replaceChildren(sanitizeNewsHtml(String(body)));
}
